const Insertion = require('./sorting/insertion')
const randomArray = require('./randomarray')
const Timer = require('./timer')
var myInsertionSort = new Insertion()

let myArray = randomArray(10)
console.log(myArray)
let myTimer = new Timer(true)
myInsertionSort.sort(myArray)
myTimer.stop()
console.log(myTimer.time)
console.log(myArray)
